apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-access
  labels:
    app: admin-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-access
  namespace: default

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-access
  namespace: default
